language: node_js
node_js:
  - "0.10"
notifications:
  email: false
sudo: false
before_install:
  - 'npm install -g grunt-cli'
  - 'gem install sass --version "=3.2.12"'
  - 'gem install compass --version "=0.12.2"'
install: npm install
before_script: grunt build