define('Nori.Events.AppEvents',
  function (require, module, exports) {
    exports.APP_INITIALIZED = 'APP_INITIALIZED';
    exports.MODEL_DATA_WAITING = 'MODEL_DATA_WAITING';
    exports.MODEL_DATA_READY = 'MODEL_DATA_READY';
    exports.MODEL_DATA_CHANGED = 'MODEL_DATA_CHANGED';
    exports.MODEL_DATA_SAVED = 'MODEL_DATA_SAVED';
    exports.MODEL_DATA_DESTROYED = 'MODEL_DATA_DESTROYED';
    exports.UPDATE_MODEL_DATA = 'UPDATE_MODEL_DATA';
    exports.RESUME_FROM_MODEL_STATE = 'RESUME_FROM_MODEL_STATE';
    exports.VIEW_INITIALIZED = 'VIEW_INITIALIZED';
    exports.VIEW_RENDERED = 'VIEW_RENDERED';
    exports.VIEW_CHANGED = 'VIEW_CHANGED';
    exports.VIEW_CHANGE_TO_MOBILE = 'VIEW_CHANGE_TO_MOBILE';
    exports.VIEW_CHANGE_TO_DESKTOP = 'VIEW_CHANGE_TO_DESKTOP';
    exports.ROUTE_CHANGED = 'ROUTE_CHANGED';
    exports.CHANGE_ROUTE = 'CHANGE_ROUTE';
    exports.SUBVIEW_STORE_STATE = 'SUBVIEW_STORE_STATE';
  });