APP.createNameSpace('APP.AppEvents');
APP.AppEvents = {

  CONTROLLER_INITIALIZED: 'CONTROLLER_INITIALIZED',

  MODEL_INITIALIZED: 'MODEL_INITIALIZED',
  MODEL_DATA_LOADED: 'MODEL_DATA_LOADED',

  RESUME_FROM_MODEL_STATE: 'RESUME_FROM_MODEL_STATE',

  VIEW_INITIALIZED: 'VIEW_INITIALIZED',
  VIEW_RENDERED: 'VIEW_RENDERED',
  VIEW_CHANGED: 'VIEW_CHANGED',

  VIEW_CHANGE_TO_MOBILE: 'VIEW_CHANGE_TO_MOBILE',
  VIEW_CHANGE_TO_DESKTOP: 'VIEW_CHANGE_TO_DESKTOP',

  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION'
};