APP.createNameSpace('APP.Events');
APP.Events = {

  CONTROLLER_INITIALIZED: 'CONTROLLER_INITIALIZED',
  URL_HASH_CHANGED: 'URL_HASH_CHANGED',

  MODEL_INITIALIZED: 'MODEL_INITIALIZED',
  MODEL_DATA_LOADED: 'MODEL_DATA_LOADED',

  RESUME_FROM_MODEL_STATE: 'RESUME_FROM_MODEL_STATE',

  VIEW_INITIALIZED: 'VIEW_INITIALIZED',
  VIEW_RENDERED: 'VIEW_RENDERED',
  VIEW_CHANGED: 'VIEW_CHANGED',
  VIEW_ALL_FILTERS_CLEARED: 'VIEW_ALL_FILTERS_CLEARED',

  MODAL_COVER_SHOW: 'MODAL_COVER_SHOW',
  MODAL_COVER_HIDE: 'MODAL_COVER_HIDE',

  BROWSER_RESIZED: 'BROWSER_RESIZED',
  BROWSER_SCROLLED: 'BROWSER_SCROLLED',
  SEARCH_INPUT: 'SEARCH_INPUT',
  ITEM_SELECT: 'ITEM_SELECT',
  MENU_SELECT: 'MENU_SELECT',
  DATA_FILTER_CHANGED: 'DATA_FILTERS_CHANGED',

  VIEW_CHANGE_TO_MOBILE: 'VIEW_CHANGE_TO_MOBILE',
  VIEW_CHANGE_TO_DESKTOP: 'VIEW_CHANGE_TO_DESKTOP',

  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',

  GRID_VIEW_ITEMS_CHANGED: 'GRID_VIEW_ITEMS_CHANGED',
  GRID_VIEW_LAYOUT_COMPLETE: 'GRID_VIEW_LAYOUT_COMPLETE',
  GRID_VIEW_IMAGE_LOAD_ERROR: 'GRID_VIEW_IMAGE_LOAD_ERROR'
};