define('TT.Events.TTEventConstants',
  function (require, module, exports) {
    exports.ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
    exports.ARCHIVE_ASSIGNMENT = 'ARCHIVE_ASSIGNMENT';
    exports.UPDATE_ASSIGNMENTS = 'UPDATE_ASSIGNMENTS';
    exports.SUBMIT_TIMECARD = 'SUBMIT_TIMECARD';
    exports.UNLOCK_TIMECARD = 'UNLOCK_TIMECARD';
    exports.UPDATE_TIMECARD = 'UPDATE_TIMECARD';
    exports.TIMECARD_WEEKFORWARD = 'TIMECARD_WEEKFORWARD';
    exports.TIMECARD_WEEKBACKWARD = 'TIMECARD_WEEKBACKWARD';
  });