nudoru.createNameSpace('nudoru.events.Events');
nudoru.events.Events = {

  URL_HASH_CHANGED: 'URL_HASH_CHANGED',

  BROWSER_RESIZED: 'BROWSER_RESIZED',
  BROWSER_SCROLLED: 'BROWSER_SCROLLED',

  VIEW_CHANGE_TO_MOBILE: 'VIEW_CHANGE_TO_MOBILE',
  VIEW_CHANGE_TO_DESKTOP: 'VIEW_CHANGE_TO_DESKTOP'

};